development:
  adapter: postgresql
  encoding: utf8
  database: workflow_app_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: workflow_app_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: workflow_app
  pool: 5